- hosts: all
  tasks:
#    - name: stop container
 #     shell:  docker container stop rockstar-container                    #name of container 
  #  - name: remove container
   #   shell: docker container rm rockstar-container
    #- name: remove docker image
     # shell: docker image rm kritig97/docker-job                            #name of images (docker images)
     - name: create new container
      shell: docker container run -itd --name dockeransible -p 9000:80 kritig97/docker-webapp     #(docker-job>> name of jenkins job)
