- hosts: all
  tasks:
    - name: stop running container
      shell:  docker container stop dockeransible                    #name of container 
    - name: remove container
      shell: docker container rm dockeransible
    - name: remove docker image
      shell: docker image rm kritig97/docker-webapp                            #name of images (docker images)
    - name: create new container
      shell: docker container run -itd --name dockeransible -p 9000:80 kritig97/docker-webapp
